### ISSUE TITLE
`docs/create-password-hashing-bcrypt`

### ISSUE THREAD

**Issue by benoit-bremaud** [benoit-bremaud/HappiHub#141]
### Issue: Création d'une Documentation sur le Hash de Mot de Passe avec Bcrypt

**Summary:**
Développer une documentation complète sur l'utilisation de Bcrypt pour le hash des mots de passe dans notre application. Cette documentation fournira des directives claires sur l'implémentation de Bcrypt, les bonnes pratiques de sécurité, et les exemples de code.

**Context:**
Le hashage des mots de passe est essentiel pour la sécurité des utilisateurs et la protection des données sensibles. Bcrypt est un algorithme de hashage robuste et couramment utilisé qui permet de sécuriser les mots de passe. Une documentation détaillée aidera les développeurs à implémenter correctement cette fonctionnalité.

**Objectives:**
- Expliquer l'importance du hashage des mots de passe.
- Fournir des exemples de code pour l'implémentation de Bcrypt.
- Décrire les bonnes pratiques de sécurité pour le stockage des mots de passe.
- Intégrer des outils et des librairies nécessaires pour utiliser Bcrypt dans notre codebase.

**Acceptance Criteria:**
- La documentation doit inclure une section sur l'importance du hashage des mots de passe.
- Des exemples de code fonctionnel doivent être fournis pour illustrer l'utilisation de Bcrypt.
- Les meilleures pratiques de sécurité pour le stockage des mots de passe doivent être clairement énoncées.
- La documentation doit être validée par au moins deux membres de l'équipe de développement.

**Tasks:**
1. **Introduction au Hashage des Mots de Passe**
   - [ ] Décrire l'importance du hashage des mots de passe.
   - [ ] Expliquer les risques de stockage des mots de passe en clair.

2. **Exemples de Code pour l'Implémentation de Bcrypt**
   - [ ] Fournir des exemples de code pour le hashage des mots de passe avec Bcrypt.
   - [ ] Fournir des exemples de code pour la vérification des mots de passe avec Bcrypt.
   - [ ] Ajouter des commentaires explicatifs dans le code.

3. **Meilleures Pratiques de Sécurité**
   - [ ] Décrire les bonnes pratiques pour le stockage des mots de passe.
   - [ ] Expliquer l'importance d'utiliser un salt unique pour chaque mot de passe.
   - [ ] Décrire comment configurer le coût de Bcrypt pour équilibrer sécurité et performance.

4. **Configuration des Librairies et Outils**
   - [ ] Fournir des instructions pour installer et configurer Bcrypt dans notre projet.
   - [ ] Expliquer comment intégrer Bcrypt avec notre système d'authentification existant.

5. **Exemples de Code**
   - **Hashage des Mots de Passe:**
     ```javascript
     const bcrypt = require('bcrypt');
     const saltRounds = 10;
     const plainPassword = 'userPassword';

     bcrypt.hash(plainPassword, saltRounds, (err, hash) => {
         if (err) {
             console.error('Error hashing password:', err);
         } else {
             console.log('Hashed password:', hash);
         }
     });
     ```

   - **Vérification des Mots de Passe:**
     ```javascript
     const bcrypt = require('bcrypt');
     const plainPassword = 'userPassword';
     const hashedPassword = 'storedHashedPassword';

     bcrypt.compare(plainPassword, hashedPassword, (err, result) => {
         if (err) {
             console.error('Error verifying password:', err);
         } else if (result) {
             console.log('Password is correct!');
         } else {
             console.log('Password is incorrect!');
         }
     });
     ```

6. **Validation et Intégration**
   - [ ] Faire relire la documentation par au moins deux développeurs.
   - [ ] Intégrer les retours et ajuster si nécessaire.

**Branch Name:** `docs/create-password-hashing-bcrypt`
