### ISSUE TITLE
`docs/create-jest-testing`

### ISSUE THREAD

**Issue by benoit-bremaud** [benoit-bremaud/HappiHub#142]
### Issue: Création d'une Documentation sur l'Utilisation des Tests avec JEST pour Node.js

**Summary:**
Développer une documentation complète sur l'utilisation de JEST pour les tests dans notre application Node.js. Cette documentation fournira des directives claires sur l'installation, la configuration, et l'écriture de tests unitaires, de tests d'intégration, de tests end-to-end (E2E) et autres tests utiles.

**Context:**
Les tests sont essentiels pour garantir la qualité et la fiabilité du code. JEST est un framework de test puissant et facile à utiliser pour les applications JavaScript, particulièrement adapté pour Node.js. Une documentation détaillée aidera les développeurs à mettre en place et à utiliser JEST efficacement.

**Objectives:**
- Expliquer l'importance des tests dans le développement logiciel.
- Fournir des instructions pour installer et configurer JEST.
- Fournir des exemples de tests unitaires, de tests d'intégration, de tests E2E et autres tests utiles.
- Décrire les meilleures pratiques pour écrire des tests maintenables et efficaces.

**Acceptance Criteria:**
- La documentation doit inclure une section sur l'importance des tests.
- Des instructions claires pour l'installation et la configuration de JEST doivent être fournies.
- Des exemples de tests unitaires, de tests d'intégration, de tests E2E et autres tests utiles doivent être inclus.
- Les meilleures pratiques pour écrire des tests doivent être clairement énoncées.
- La documentation doit être validée par au moins deux membres de l'équipe de développement.

**Tasks:**
1. **Introduction aux Tests**
   - [ ] Décrire l'importance des tests dans le développement logiciel.
   - [ ] Expliquer les différents types de tests (unitaires, d'intégration, end-to-end, de performance, etc.).

2. **Installation et Configuration de JEST**
   - [ ] Fournir des instructions pour installer JEST dans un projet Node.js.
   - [ ] Expliquer comment configurer JEST (fichier de configuration, scripts npm).

3. **Écriture de Tests Unitaires avec JEST**
   - [ ] Fournir des exemples de tests unitaires simples.
   - [ ] Expliquer les différentes méthodes et assertions disponibles dans JEST.
   - [ ] Ajouter des commentaires explicatifs dans le code.

4. **Écriture de Tests d'Intégration avec JEST**
   - [ ] Fournir des exemples de tests d'intégration.
   - [ ] Expliquer comment configurer et utiliser des mocks et des spies dans JEST.
   - [ ] Ajouter des commentaires explicatifs dans le code.

5. **Écriture de Tests End-to-End (E2E) avec JEST**
   - [ ] Expliquer l'importance des tests E2E.
   - [ ] Fournir des exemples de tests E2E utilisant des outils comme Puppeteer ou Selenium.
   - [ ] Expliquer comment configurer l'environnement de test E2E.

6. **Écriture de Tests de Performance**
   - [ ] Décrire l'importance des tests de performance.
   - [ ] Fournir des exemples de tests de performance pour mesurer la réactivité et l'efficacité du code.

7. **Meilleures Pratiques pour les Tests**
   - [ ] Décrire les bonnes pratiques pour écrire des tests maintenables et efficaces.
   - [ ] Expliquer comment organiser les fichiers de tests.
   - [ ] Fournir des conseils pour écrire des tests clairs et compréhensibles.

8. **Exemples de Code**
   - **Test Unitaire:**
     ```javascript
     const sum = (a, b) => a + b;

     test('adds 1 + 2 to equal 3', () => {
         expect(sum(1, 2)).toBe(3);
     });
     ```

   - **Test d'Intégration:**
     ```javascript
     const request = require('supertest');
     const app = require('./app');

     describe('GET /api/users', () => {
         it('responds with json containing a list of all users', async () => {
             const response = await request(app).get('/api/users');
             expect(response.statusCode).toBe(200);
             expect(response.body).toBeInstanceOf(Array);
         });
     });
     ```

   - **Test End-to-End (E2E):**
     ```javascript
     const puppeteer = require('puppeteer');

     describe('E2E Test', () => {
         it('should navigate to the home page and check the title', async () => {
             const browser = await puppeteer.launch();
             const page = await browser.newPage();
             await page.goto('http://localhost:3000');
             const title = await page.title();
             expect(title).toBe('Home Page');
             await browser.close();
         });
     });
     ```

   - **Test de Performance:**
     ```javascript
     const { performance } = require('perf_hooks');

     test('performance test', () => {
         const start = performance.now();
         // Function to test
         const end = performance.now();
         const duration = end - start;
         console.log(`Duration: ${duration}ms`);
         expect(duration).toBeLessThan(1000); // Example threshold
     });
     ```

9. **Validation et Intégration**
   - [ ] Faire relire la documentation par au moins deux développeurs.
   - [ ] Intégrer les retours et ajuster si nécessaire.

**Branch Name:** `docs/create-jest-testing`
