### ISSUE TITLE
`feature/update-comment-by-id-put`

### ISSUE THREAD

**Issue by benoit-bremaud** [benoit-bremaud/HappiHub#150]
### Summary
Créer une route `PUT /comments/:id` qui permet de mettre à jour complètement un commentaire spécifique en utilisant son ID. Cette route sera accessible à tous les utilisateurs authentifiés et devra vérifier que l'utilisateur est l'auteur du commentaire ou un administrateur.

### Context
Pour permettre aux utilisateurs de mettre à jour leurs propres commentaires et aux administrateurs de modérer les commentaires, il est nécessaire de créer une route qui permet la mise à jour complète des commentaires.

### Objectives
- Créer une route `PUT /comments/:id` pour mettre à jour complètement un commentaire spécifique.
- Assurer que la route vérifie l'authentification de l'utilisateur avant de procéder à la mise à jour.
- Assurer que la mise à jour est effectuée uniquement par l'auteur du commentaire ou un administrateur.

### Acceptance Criteria
- La route `PUT /comments/:id` doit être créée et permettre la mise à jour complète des informations du commentaire correspondant à l'ID fourni.
- La route doit être protégée par une vérification d'authentification (`authenticateToken`).
- La route doit vérifier que l'utilisateur est l'auteur du commentaire ou un administrateur avant d'autoriser la mise à jour.
- Si le commentaire n'est pas trouvé, la route doit renvoyer une réponse appropriée (`404 Not Found`).
- Les tests unitaires doivent être mis à jour pour couvrir ce nouveau comportement.
- La documentation de l'API doit être mise à jour pour refléter cette nouvelle route.

### Tasks
- [x] Créer la route `PUT /comments/:id` dans le contrôleur des commentaires.
- [x] Ajouter la vérification d'authentification (`authenticateToken`) à cette route.
- [x] Ajouter la vérification de l'auteur du commentaire ou de l'administrateur.
- [x] Gérer les cas où le commentaire n'est pas trouvé et renvoyer une réponse `404 Not Found`.
- [ ] Mettre à jour les tests unitaires pour inclure des cas de test pour cette nouvelle route.
- [ ] Mettre à jour la documentation de l'API pour inclure la nouvelle route `PUT /comments/:id`.

### Resources
- [Express.js Documentation](https://expressjs.com/)
- [Mongoose Documentation](https://mongoosejs.com/docs/guide.html)

### UML Diagrams References
- **Sequence Diagram** : Pour visualiser le flux d'opérations lors de la requête `PUT /comments/:id`.

### Branch Name
`feature/update-comment-by-id-put`
