### ISSUE TITLE
`feature/comment-reporting`

### ISSUE THREAD

**Issue by benoit-bremaud** [benoit-bremaud/HappiHub#162]
### Summary
Implémenter des fonctionnalités de rapport de commentaires pour permettre aux utilisateurs de signaler des commentaires inappropriés ou abusifs, et aux administrateurs de gérer ces rapports.

### Context
Pour améliorer la modération et la sécurité de la plateforme, il est important de permettre aux utilisateurs de signaler les commentaires inappropriés et de fournir aux administrateurs les outils nécessaires pour gérer ces rapports.

### Objectives
- Ajouter une route pour permettre aux utilisateurs de signaler des commentaires.
- Ajouter des fonctionnalités pour que les administrateurs puissent voir et gérer les rapports de commentaires.

### Acceptance Criteria
- Les utilisateurs doivent pouvoir signaler des commentaires via une nouvelle route.
- Les administrateurs doivent pouvoir voir et gérer les rapports de commentaires.
- Les tests unitaires doivent être mis à jour pour couvrir ces nouveaux comportements.
- La documentation de l'API doit être mise à jour pour refléter les fonctionnalités de rapport de commentaires.

### Tasks
- [ ] Créer une route pour permettre aux utilisateurs de signaler des commentaires.
- [ ] Créer des fonctionnalités pour permettre aux administrateurs de voir et gérer les rapports de commentaires.
- [ ] Mettre à jour les tests unitaires pour inclure des cas de test pour les rapports de commentaires.
- [ ] Mettre à jour la documentation de l'API pour inclure des informations sur les rapports de commentaires.

### Resources
- [Express.js Documentation](https://expressjs.com/)
- [Mongoose Documentation](https://mongoosejs.com/docs/guide.html)

### UML Diagrams References
- **Sequence Diagram** : Pour visualiser le flux d'opérations lors des rapports de commentaires et de leur gestion.

### Branch Name
`feature/comment-reporting`
