### ISSUE TITLE
`feature/comment-threads`

### ISSUE THREAD

**Issue by benoit-bremaud** [benoit-bremaud/HappiHub#167]
### Summary
Ajouter la possibilité pour les utilisateurs de répondre à des commentaires, créant ainsi des discussions en thread pour améliorer l'interaction et l'engagement sur la plateforme.

### Context
Les discussions en thread permettent une meilleure organisation des commentaires et des réponses, facilitant les conversations et les suivis.

### Objectives
- Ajouter un champ `parentCommentId` au modèle de commentaire pour lier les réponses à leur commentaire parent.
- Créer des routes pour permettre de répondre à un commentaire.
- Modifier les routes existantes pour récupérer les commentaires avec leurs réponses.

### Acceptance Criteria
- Les utilisateurs doivent pouvoir répondre à des commentaires en utilisant un champ `parentCommentId`.
- Les commentaires récupérés doivent inclure leurs réponses sous forme de threads.
- Les tests unitaires doivent être mis à jour pour couvrir ces nouvelles fonctionnalités.
- La documentation de l'API doit être mise à jour pour inclure les informations sur les threads de commentaires.

### Tasks
- [ ] Ajouter le champ `parentCommentId` au modèle de commentaire.
- [ ] Créer des routes pour permettre de répondre à un commentaire.
- [ ] Modifier les routes existantes pour récupérer les commentaires avec leurs réponses.
- [ ] Mettre à jour les tests unitaires pour inclure des cas de test pour les threads de commentaires.
- [ ] Mettre à jour la documentation de l'API pour inclure des informations sur les threads de commentaires.

### Resources
- [Express.js Documentation](https://expressjs.com/)
- [Mongoose Documentation](https://mongoosejs.com/docs/guide.html)

### UML Diagrams References
- **Sequence Diagram** : Pour visualiser le flux d'opérations lors de la création et de la récupération des réponses aux commentaires.

### Branch Name
`feature/comment-threads`
