### ISSUE TITLE
feat: Créer la route POST /api/events/:id/participate

### ISSUE THREAD

**Issue by benoit-bremaud** [benoit-bremaud/HappiHub#8]
### Résumé
Créer une route POST `/api/events/:id/participate` pour permettre aux utilisateurs authentifiés de participer à des événements.

### Contexte
Les utilisateurs doivent pouvoir participer aux événements disponibles sur la plateforme HappiHub.

### Objectifs
- Créer une route POST `/api/events/:id/participate`.
- Vérifier l'authentification de l'utilisateur.
- Ajouter l'utilisateur à la liste des participants de l'événement.
- Renvoyer une réponse appropriée après participation.

### Livrables
- Route de participation à un événement fonctionnelle.

### Critères d'Acceptation
- La route doit vérifier que l'utilisateur est authentifié.
- L'utilisateur doit être ajouté à la liste des participants de l'événement.
- Une réponse JSON doit être renvoyée indiquant le succès ou l'échec de la participation.

### Tâches
- [ ] Créer la route POST `/api/events/:id/participate` dans le contrôleur événement.
- [ ] Vérifier l'authentification de l'utilisateur.
- [ ] Ajouter l'utilisateur à la liste des participants de l'événement.
- [ ] Renvoyer une réponse appropriée après participation.

### Ressources
- [Express.js Documentation](https://expressjs.com/)
- [JWT Documentation](https://jwt.io/introduction/)
- [Mongoose Documentation](https://mongoosejs.com/)

### Diagrammes UML Référents
- **Diagramme de Cas d'Utilisation** : Pour comprendre les interactions de l'utilisateur avec le système lors de la participation à des événements.
- **Diagramme de Séquence** : Pour visualiser le flux des opérations depuis la requête de participation jusqu'à la réponse du serveur.
- **Diagramme de Classe** : Pour voir la structure du modèle événement et ses relations avec les utilisateurs.

### Nom de la Branche
`feature/participate-event`

### Étiquettes
- `backend` : Related to server-side code
- `feature` : New functionality to be added
- `security` : Related to authentication and authorization

### Milestone Suggestion
`Milestone 2: Event Management`

**Comment by benoit-bremaud** [comment]
### Plan pour les Tests Avancés avec Postman

#### 1. **Créer un Environnement Postman**

1.1 **Définir les Variables d'Environnement**
- Accédez à l'onglet "Environments" dans Postman et créez un nouvel environnement.
- Ajoutez les variables suivantes :
  - `baseUrl`: URL de base de votre API (ex. : `http://localhost:3000/api`)
  - `authToken`: Token d'authentification (laissez la valeur vide pour le moment)
  - `eventId`: ID de l'événement à tester (laissez la valeur vide pour le moment)
  - `userId`: ID de l'utilisateur à tester (laissez la valeur vide pour le moment)

#### 2. **Créer une Collection Postman**

2.1 **Créer une Nouvelle Collection**
- Cliquez sur "New" -> "Collection" et nommez-la (ex. : `HappiHub API Tests`).

2.2 **Ajouter une Documentation de Collection**
- Ajoutez une description générale de votre API et des objectifs de la collection.

#### 3. **Configurer les Requêtes de Test**

3.1 **Requête pour Authentifier l'Utilisateur**
- **Méthode** : `POST`
- **URL** : `{{baseUrl}}/auth/login`
- **Body** : (format JSON, exemple) :
  ```json
  {
      "email": "user@example.com",
      "password": "password123"
  }
  ```
- **Tests** :
  ```javascript
  const response = pm.response.json();
  pm.environment.set('authToken', response.token);
  ```

3.2 **Requête pour Récupérer un Événement**
- **Méthode** : `GET`
- **URL** : `{{baseUrl}}/events/{{eventId}}`
- **Headers** :
  - `Authorization: Bearer {{authToken}}`

3.3 **Requête pour Ajouter un Utilisateur aux Participants**
- **Méthode** : `PATCH`
- **URL** : `{{baseUrl}}/events/{{eventId}}/attendees`
- **Headers** :
  - `Authorization: Bearer {{authToken}}`
- **Body** : (format JSON, exemple) :
  ```json
  {
      "userId": "{{userId}}"
  }
  ```
- **Tests** :
  ```javascript
  pm.test("Status code is 200", function () {
      pm.response.to.have.status(200);
  });

  pm.test("User added to event attendees", function () {
      const response = pm.response.json();
      pm.expect(response.message).to.eql("User added to event attendees");
  });
  ```

#### 4. **Ajouter des Tests Automatisés**

4.1 **Vérifier les Réponses**
- Pour chaque requête, ajoutez des tests pour vérifier les réponses :
  - **Status Code** : Vérifiez que le code de statut est correct (200 pour une requête réussie, 404 pour une ressource non trouvée, etc.).
  - **Body Content** : Vérifiez que le contenu de la réponse est correct (ex. : message de confirmation, structure des données).

4.2 **Vérifier les Scénarios d'Erreur**
- Ajoutez des tests pour les scénarios d'erreur :
  - **Utilisateur déjà participant** : Vérifiez que le message d'erreur est correct si l'utilisateur est déjà participant.
  - **Événement non trouvé** : Vérifiez que le message d'erreur est correct si l'événement n'existe pas.
  - **Utilisateur non trouvé** : Vérifiez que le message d'erreur est correct si l'utilisateur n'existe pas.

#### 5. **Gérer la Documentation Dynamique**

5.1 **Utiliser des Descriptions Détaillées**
- Pour chaque requête, ajoutez des descriptions détaillées :
  - **Objectif de la Requête** : Expliquez ce que fait la requête.
  - **Paramètres** : Décrivez les paramètres de la requête (URL, headers, body).
  - **Exemples de Réponse** : Ajoutez des exemples de réponses réussies et d'erreurs.

5.2 **Générer la Documentation API**
- Utilisez Postman pour générer automatiquement la documentation API à partir de la collection :
  - Accédez à la collection -> Cliquez sur "View in web" -> Utilisez "Generate documentation".

#### 6. **Exécution des Tests et Mise à Jour de la Documentation**

6.1 **Exécuter les Tests**
- Utilisez l'onglet "Runner" de Postman pour exécuter l'ensemble des tests de la collection.
- Vérifiez les résultats des tests pour vous assurer que toutes les requêtes fonctionnent comme prévu.

6.2 **Mettre à Jour la Documentation**
- Après avoir validé les tests, mettez à jour la documentation générée pour refléter les changements et les nouveaux tests.

### Intégration avec GitHub Actions

Pour automatiser l'exécution des tests et la mise à jour de la documentation, vous pouvez utiliser GitHub Actions :

#### Configuration de GitHub Actions

1. **Utiliser `newman` pour exécuter des collections Postman** :
   - Installez `newman` globalement si ce n'est pas déjà fait :
     ```bash
     npm install -g newman
     ```

2. **Ajouter un script d'exécution des tests dans votre `package.json`** :
   - Ouvrez `package.json` et ajoutez un script pour exécuter les tests Postman :
     ```json
     "scripts": {
       "test:postman": "newman run path/to/HappiHub_API_Tests.postman_collection.json -e path/to/MERN_Project_Environment.postman_environment.json"
     }
     ```

3. **Configurer GitHub Actions pour les tests automatiques** :
   - Créez un fichier `.github/workflows/postman-tests.yml` :
     ```yaml
     name: Run Postman Tests

     on:
       push:
         branches:
           - main

     jobs:
       postman-tests:
         runs-on: ubuntu-latest

         steps:
           - name: Checkout code
             uses: actions/checkout@v2

           - name: Setup Node.js
             uses: actions/setup-node@v2
             with:
               node-version: '14'

           - name: Install dependencies
             run: npm install

           - name: Run Postman tests
             run: npm run test:postman
     ```

### Exemple de procédure de test avec Postman

1. **Ouvrir Postman et sélectionner l'environnement `MERN_Project`.**
2. **Assurez-vous que le serveur de votre API est en cours d'exécution.**
3. **Exécuter la requête `Participate in Event` avec les bons paramètres.**
4. **Vérifier les résultats des tests dans l'onglet `Tests`.**
5. **Publier la documentation mise à jour si des changements sont apportés.**
